### ISSUE TITLE
为啥snr是随机出来的？

### ISSUE THREAD

**Issue by srdfjy** [YongyuG/separation_data_preparation#9]
为啥snr是随机出来的？不是根据2个文件算出来的呢？

**Comment by YongyuG** [comment]
> 为啥snr是随机出来的？不是根据2个文件算出来的呢？

因为这里的snr是混合的音频的信噪比，
通过这个随机出来的信噪比，对干净信号或者噪声信号进行缩放使他们在叠加的时候能达到我们期望的信噪比

**Comment by srdfjy** [comment]
我看你用的范围是0-2.5，wsj0用的是0-5，实际情况这个范围如何选择呢，谢谢！
